ALTER TABLE servers ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMP;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS suspension_reason TEXT;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS mode VARCHAR(20) NOT NULL DEFAULT 'live';
ALTER TABLE servers ADD COLUMN IF NOT EXISTS send_limit INTEGER;
